### ISSUE TITLE
Epic 2 User Story 2: Implement functionality to POST a new activity.

### ISSUE THREAD

**Issue by Mahik99** [SchoolOfCode/bc17-w4d2-project-t-21#4]
Description:

As Kenny, a busy front end engineer I need to be able to send a POST request with a JSON request body (new activity) to the API so that I can make a simple form that allows my user to submit new activity.

As Norman, a Tech Lead working across lots of projects I need to be able to depend on conventions like: the response object always containing a key called data or error, or the status code being an accurate indication of the success/failure (and reason) of the request.

Acceptance Criteria:

Given I am a developer who has the Activity API running,
When I make a POST request to “http://localhost:3000/activities” with a request body containing a JSON object (new activity),
Then the API should save the new activity to the activities.json file giving it a unique “id” (UUID) and activity_submitted (time stamp - Date.now()),
Then the the request should succeed, responding with the correct status code and the activity object that I posted as the response body (response.data).

Given I am a developer who has made an invalid POST request by missing a required request body field like, activity_type or activity_duration,
When I inspect the API response,
Then the request should fail, responding with the correct status code and a clear error message (response.error).
```[tasklist]
### Tasks
- [x] Create a POST request to http://localhost:3000/activities
- [x] Enter the new activity in the request body as a JSON object
- [x] Create a function js file and export this to our app.js file
- [x] Create activities.json file
- [x] Create an async function to save the new activity, take in the input of request body as a parameter.
- [x] add timestamp for activity_submitted
- [x] Respond with 200 status code and activity object when the request succeeds.
- [x] If an invalid POST request is made (missing request body/activity_type/activity_duration) it should respond with the 400/406 status code and error message
```
